### ISSUE TITLE
.db is a hidden file

### ISSUE THREAD

**Issue by CamilleScholtz** [anoma-/mypass#1]
I understand the `~/.mypass` dir being a dotfile, however, the .db file is already "hidden" from view, wouldn't something like `~/.mypass/database` be more logical (and common) than `~/.mypass/.db`

**Comment by anoma-** [comment]
Yes, it isn't that important that the db file be hidden. I did think about changing that, but I figured it didn't affect much being hidden. And it is rather important that no bits change in the db file, as it is authenticated. So a 1 bit change would leave the db unusable.... so I opted to leave it as it was. However, I'm not opposed to changing that for a 1.0 release. On a side note, please be sure you have the 0.9.1 version. There was an initial bug that would alter the user salt, that is generated when creating a new database.

**Comment by anoma-** [comment]
Any other suggestions are appreciated
